version: "3.8"
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: tukko-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-stack.conf:/redis-stack.conf

  mongo:
    image: mongo:jammy
    container_name: tukko-archive
    env_file:
      - .env
