version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: travis-redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis-stack.conf:/redis-stack.conf

  mongoDB:
    image: mongo:jammy
    container_name: travis-archive
    env_file:
      - .env
      - .env.override
    ports:
      - "2717:27017"