version: '3.8'
services:
  tv-api:
    depends_on:
      - redis-stack
      - mongoDB
    container_name: travis-app
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    command: sh -c "node dist/index.js"

  redis-stack:
    image: redis/redis-stack:latest
    container_name: travis-redis
    restart: on-failure
    ports:    
     - 6379:6379
     - 8001:8001
    volumes:
     - ./redis-stack.conf:/redis-stack.conf
    
  mongoDB:
    image: mongo:jammy
    container_name: travis-archive
    env_file:
      - .env
    ports:
      - "2717:27017"