version: '3.8'
services:
  tv-api:
    depends_on:
      - redis-stack
      - mongoDB
    image: node:alpine
    working_dir: /app
    container_name: tukko-app
    restart: always
    env_file:
      - .env
      - .env.override
    ports:
      - "3001:3001"
    volumes:
      - ./dist/:/app/dist
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: sh -c "npm i --omit-dev && node dist/index.js"

  redis-stack:
    image: redis/redis-stack:latest
    container_name: tukko-redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis-stack.conf:/redis-stack.conf

  mongoDB:
    image: mongo:jammy
    container_name: tukko-archive
    env_file:
      - .env
      - .env.override
    ports:
      - "2717:27017"