version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: tukko-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-stack.conf:/redis-stack.conf

  mongoDB:
    image: mongo:jammy
    container_name: tukko-archive
    env_file:
      - .env

  tv-api:
    depends_on:
      - redis-stack
      - mongoDB
    build: .
    container_name: tukko-app
    restart: always
    environment:
      REDIS_OM_URL: "redis://redis-stack:6379"
      DB_CONN_STRING: "mongodb://admin:admin@mongoDB:27017"
    ports:
      - "3001:3001"

